### ISSUE TITLE
Resize hero image please 

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/First-Year-Writing-Program#1]
Hey Zac Attack! Could you please resize the hero for me when you get a chance, thanks! 

FYWP image.jpeg- It's in the media folder

**Comment by ZMcGroarty** [comment]
![hero_fyw-min](https://user-images.githubusercontent.com/15017242/34734134-b91e2f00-f538-11e7-8891-3cd1e306cd60.png)

**Comment by CVE82** [comment]
Thank you!

**Comment by ZMcGroarty** [comment]
![hero_fyw-nohue-min](https://user-images.githubusercontent.com/15017242/34789626-f7e8bcee-f60c-11e7-9667-56312e0c9a3c.png)

**Comment by CVE82** [comment]
You're awesome, thank you!
